[project]
name = "dbt-inline-docs"
version = "0.1.0"
description = "Write inline Javadoc-style dbt model & column docs (no more separate YAML files!)"
readme = "README.md"
authors = [
    { name = "Tim Vergenz", email = "vergenzt@gmail.com" },
]
requires-python = ">=3.8"
dependencies = [
    "dbt-core>=1.6",
]

[dependency-groups]
dev = [
    "hatch",
    "pytest",
    "dbt-postgres",
    "tinypg",
    "dbt-subprocess-plugin",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
